import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { JobDetail } from '@/types/domain'
import { JOB_STATUS_CONFIG, JOB_PRIORITY_CONFIG } from '@/types/domain'
import { formatDate as fmtDate, formatCurrency as fmtCurrency } from '@/lib/utils'

export function generateJobPDF(job: JobDetail): Blob {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()

  // Header bar
  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, W, 18, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Guidant 365 — Job Report', 14, 12)

  // Job title
  doc.setTextColor(15, 23, 42)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(job.title, 14, 30)

  // Status + priority badges
  const statusCfg = JOB_STATUS_CONFIG[job.status]
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`Status: ${statusCfg.label}   Priority: ${JOB_PRIORITY_CONFIG[job.priority].label}`, 14, 37)

  // Customer section
  if (job.customer) {
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text('Customer', 14, 47)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(job.customer.name, 14, 53)
    if (job.customer.email) doc.text(job.customer.email, 14, 58)
    if (job.customer.phone) doc.text(job.customer.phone, 14, 63)
  }

  // Dates + next action
  let yPos = job.customer ? 75 : 47
  autoTable(doc, {
    startY: yPos,
    head: [['Field', 'Value']],
    body: [
      ['Start Date', job.start_date ? fmtDate(job.start_date) : '—'],
      ['End Date', job.end_date ? fmtDate(job.end_date) : '—'],
      ['Next Action', job.next_action ?? '—'],
      ['Next Due', job.next_due ? fmtDate(job.next_due) : '—'],
      ['Notes', job.notes ?? '—'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
  })

  // Invoices
  if (job.invoices.length > 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    yPos = (doc as any).lastAutoTable.finalY + 10
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(15, 23, 42)
    doc.text('Invoices', 14, yPos)
    autoTable(doc, {
      startY: yPos + 4,
      head: [['Amount', 'Paid', 'Due Date', 'Status']],
      body: job.invoices.map(inv => [
        fmtCurrency(Number(inv.amount)),
        fmtCurrency(Number(inv.paid_amount)),
        inv.due_date ? fmtDate(inv.due_date) : '—',
        inv.status.toUpperCase(),
      ]),
      theme: 'striped',
      headStyles: { fillColor: [30, 64, 175] },
    })
  }

  // Timeline
  if (job.timeline.length > 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    yPos = (doc as any).lastAutoTable.finalY + 10
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(15, 23, 42)
    doc.text('Timeline', 14, yPos)
    autoTable(doc, {
      startY: yPos + 4,
      head: [['Date', 'Type', 'Content']],
      body: job.timeline.map(t => [
        fmtDate(t.created_at),
        t.type,
        t.content.slice(0, 100),
      ]),
      theme: 'grid',
      headStyles: { fillColor: [30, 64, 175] },
      columnStyles: { 2: { cellWidth: 100 } },
    })
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Generated by Guidant 365 on ${fmtDate(new Date())}   |   Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.getHeight() - 8
    )
  }

  return doc.output('blob')
}

export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
